language: node_js
node_js:
- 6.11.0
before_install:
- openssl aes-256-cbc -K $encrypted_82cfc9e05a23_key -iv $encrypted_82cfc9e05a23_iv
  -in id_rsa.enc -out id_rsa -d

- mv id_rsa ~/.ssh -f
- chmod 600 ~/.ssh/id_rsa

# 配置 ssh
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config

after_script:
- scp -o StrictHostKeyChecking=no app.js root@t.tstoon.com:/root/nodetest